encryptionsalt: v1:cAPbxz5qq94=:v1:FoLbd7ETvxeBe6im:OrEs1FFO0KsQ536nwtkHcu28thRFGw==
config:
  aws:region: ap-southeast-2
  infrastructure:dbEndpoint: https://dynamodb.ap-southeast-2.amazonaws.com
  infrastructure:env: stage
  infrastructure:githubOwner: intersective
  infrastructure:githubToken:
    secure: v1:neFOFeOaIQQ8U9aY:BGJqONjL1m6VRuEbzbNrwu6oYai7bDP8ie/jupZk2Tod2q1T3Zq1+SRKMGDkgdWdiGFAlF8/tCE=
  infrastructure:lambdaBasicExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  infrastructure:lambdaDynamoDBExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
  infrastructure:lambdaFunctionName: slack_pr_lambda
  infrastructure:lambdaRoleName: slack_pr_lambda_role
  infrastructure:region: ap-southeast-2
  infrastructure:slackChannel: C06Q1FDPTUZ
  infrastructure:slackToken:
    secure: v1:Cx8Z3B92V5QElbr9:mlEMhwLI4QV3otMTRh30CXP3Xp130KCj0tQFQWVj/gwC5BMThPX2p0bFC7ymXqQdlYE3mFe8J/UXgrB1S5/Wv74VK++5WQ==
  infrastructure:tableName: PullRequests
  infrastructure:tableNameIndex: PullRequestIdIndex
  pulumi:tags:
    automated: "true"
    team: DevOps
    tool: pulumi
