encryptionsalt: v1:cAPbxz5qq94=:v1:FoLbd7ETvxeBe6im:OrEs1FFO0KsQ536nwtkHcu28thRFGw==
config:
  aws:region: ap-southeast-2
  infrastructure:dbEndpoint: https://dynamodb.ap-southeast-2.amazonaws.com
  infrastructure:env: stage
  infrastructure:githubOwner: intersective
  infrastructure:githubToken:
    secure: v1:neFOFeOaIQQ8U9aY:BGJqONjL1m6VRuEbzbNrwu6oYai7bDP8ie/jupZk2Tod2q1T3Zq1+SRKMGDkgdWdiGFAlF8/tCE=
  infrastructure:lambdaBasicExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  infrastructure:lambdaDynamoDBExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
  infrastructure:lambdaFunctionName: slack_pr_lambda
  infrastructure:lambdaRoleName: slack_pr_lambda_role
  infrastructure:region: ap-southeast-2
  infrastructure:slackChannel: C06Q1FDPTUZ
  infrastructure:slackToken:
    secure: v1:LdaGPrk8RS/4pJRS:sLVLLo12yKx8QS/6q9HJXHPVNPhn90VYvnwHn7Uif3OZuLn9CJiSq19UXo7JC6GjK4MtaCpG0K2zosOGJdbjJCo3HmeuNA==
  infrastructure:tableName: PullRequests
  infrastructure:tableNameIndex: PullRequestIdIndex
  pulumi:tags:
    automated: "true"
    team: DevOps
    tool: pulumi
